"""init1

Revision ID: 1511f73ed20f
Revises: 
Create Date: 2025-06-17 12:44:45.220225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1511f73ed20f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('diagnosis', sa.TEXT(), nullable=False),
    sa.Column('treatment', sa.TEXT(), nullable=True),
    sa.Column('record_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
