"""payment_intent_id on client_self_create_appointment

Revision ID: 4246b15ba905
Revises: 930c32e7c702
Create Date: 2026-03-05 21:39:44.914135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4246b15ba905'
down_revision = '930c32e7c702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_self_create_appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_intent_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_self_create_appointment', schema=None) as batch_op:
        batch_op.drop_column('payment_intent_id')

    # ### end Alembic commands ###
