"""empty message

Revision ID: 78190f3d9f40
Revises: 8552ed072190
Create Date: 2025-07-01 14:26:56.280098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78190f3d9f40'
down_revision = '8552ed072190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.alter_column('documents',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('adress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adress', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('documents',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('address')
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
