"""empty message

Revision ID: 8552ed072190
Revises: 85dbfdd07ddd
Create Date: 2025-07-01 13:38:32.878262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8552ed072190'
down_revision = '85dbfdd07ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(), nullable=True))
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
