"""empty message

Revision ID: 85dbfdd07ddd
Revises: 
Create Date: 2025-06-28 12:19:09.604584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85dbfdd07ddd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('documents', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('adress', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('adress')
        batch_op.drop_column('about_me')
        batch_op.drop_column('date_birth')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('documents')
        batch_op.drop_column('full_name')
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
