"""terms_accepted has_insurance insurance_document profile_visibility

Revision ID: 930c32e7c702
Revises: 4045b6636fe4
Create Date: 2026-03-05 15:45:39.174457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930c32e7c702'
down_revision = '4045b6636fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_accepted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_insurance', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('insurance_document', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('profile_visibility', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_visibility')
        batch_op.drop_column('insurance_document')
        batch_op.drop_column('has_insurance')
        batch_op.drop_column('terms_accepted')

    # ### end Alembic commands ###
