"""add tags and district fields

Revision ID: f82761e2d76a
Revises: f1a2b3c4d5e6
Create Date: 2026-03-07 17:50:08.478445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82761e2d76a'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_self_create_appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('service_tags', sa.String(length=500), nullable=True))

    with op.batch_alter_table('provider_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_service', schema=None) as batch_op:
        batch_op.drop_column('tags')

    with op.batch_alter_table('client_self_create_appointment', schema=None) as batch_op:
        batch_op.drop_column('service_tags')
        batch_op.drop_column('district')

    # ### end Alembic commands ###
